version: "3"
services:
  myreact_dev:
      build:
        context: .
        dockerfile: Dockerfile.dev
      ports:
          - "3000:3000"
      volumes:
          - /var/app/node_modules
          - .:/var/app

  myreact_qa:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /var/app/node_modules
            - .:/var/app
        command: ["npm","run","test"]